// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taschenrechner.Daten;

#nullable disable

namespace Taschenrechner.Migrations
{
    [DbContext(typeof(TaschenrechnerContext))]
    partial class TaschenrechnerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Taschenrechner.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("eigabePasswort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vorherigeOprationen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Taschenrechner.Rechnung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ergebnis")
                        .HasColumnType("REAL");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Zahl")
                        .HasColumnType("REAL");

                    b.Property<double>("Zahl2")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Rechnungen");
                });
#pragma warning restore 612, 618
        }
    }
}
